repos:
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black
    -   id: black-jupyter
-   repo: https://github.com/nbQA-dev/nbQA
    rev: 1.6.3
    hooks:
    -   id: nbqa-ruff
        additional_dependencies: [ruff==0.0.256]
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.256
    hooks:
    -   id: ruff
        args: [--exit-non-zero-on-fix]
