name: carmapy
channels:
  - defaults
  - conda-forge
dependencies:
  - beautifulsoup4=4.9.3
  - geopandas=0.8.1
  - geopy=2.1.0
  - jupyterlab=3.0.14
  - pandas=1.2.4
  - pandas-datareader=0.9.0
  - pip
  - plotly=4.14.3
  - pyarrow=4.0.1
  - python=3.8
  - textblob=0.15.3
  - pip:
    - pynytimes==0.6.1
    - wrds==3.0.10
