name: carmapytest
channels:
  - conda-forge
  - defaults
dependencies:
  - beautifulsoup4=4.10.0
  - geopandas=0.9.0
  - geopy=2.2.0
  - jupyterlab=3.2.1
  - nodejs=16.6.1
  - pandas=1.3.4
  - pandas-datareader=0.10.0
  - pip
  - plotly=5.1.0
  - pyarrow=4.0.1
  - python=3.9
  - textblob=0.15.3
  - pip:
    - pynytimes==0.7.0
    - wrds==3.1.1
