name: carmapy
channels:
  - defaults
  - conda-forge
dependencies:
  - jupyterlab=3.0.14
  - pandas=1.2.4
  - plotly=4.14.3
  - pyarrow=3.0.0
  - python=3.8
  - textblob=0.15.3
  - pip:
    - pynytimes==0.6.1
