name: carmapy
channels:
  - conda-forge
dependencies:
  - beautifulsoup4=4.11.1
  - geopandas=0.10.2
  - geopy=2.2.0
  - jupyterlab=3.4.2
  - nodejs=16.6.1
  - pandas=1.4.2
  - pandas-datareader=0.10.0
  - pip
  - plotly=5.8.0
  - pyarrow=8.0.0
  - python=3.10
  - textblob=0.15.3
  - pip:
    - pynytimes==0.8.0
    - wrds==3.1.1
